INSERT INTO 'warna' ('id_warna','id_jenis', 'warna', 'warna_src')
VALUES
    (NULL, '22', 'Attitude Black'	, 'https://www.toyota.astra.co.id/sites/default/files/2020-08/hilux-s-cab-dsl-4x4-colors-attitude-black%20688x408.png'),
    (NULL, '22', 'Crimson Red'	, 'https://www.toyota.astra.co.id/sites/default/files/2020-08/hilux-s-cab-dsl-4x4-colors-crimson-red%20688x408.png'),
    (NULL, '22', 'Dark Mika Metallic'	, 'https://www.toyota.astra.co.id/sites/default/files/2020-08/hilux-s-cab-dsl-4x4-colors-dark-gray-mica-metallic%20688x408.png'),
    (NULL, '22', 'Super White'	, 'https://www.toyota.astra.co.id/sites/default/files/2020-08/hilux-s-cab-dsl-4x4-colors-super-white%20688x408.png'),
    (NULL, '22', 'Silver Metalic'	, 'https://www.toyota.astra.co.id/sites/default/files/2020-08/hilux-s-cab-dsl-4x4-colors-silver-metallic%20688x408.png'),
    (NULL, '23', 'Attitude Black'	, 'https://static.rajamobil.com/resize/289x182/media/images/databasemobil/mobilbaru/color/hilux-black.png'),
    (NULL, '23', 'Crimson Red'	, 'https://static.rajamobil.com/resize/289x182/media/images/databasemobil/mobilbaru/color/hilux-red.png'),
    (NULL, '23', 'Dark Mika Metallic'	, 'https://static.rajamobil.com/resize/289x182/media/images/databasemobil/mobilbaru/color/hilux-grey.png'),
    (NULL, '23', 'Silver Metalic'	, 'https://static.rajamobil.com/resize/289x182/media/images/databasemobil/mobilbaru/color/hilux-silver.png'),
    (NULL, '23', 'Super White'	, 'https://static.rajamobil.com/resize/289x182/media/images/databasemobil/mobilbaru/color/hilux-white.png'),
    (NULL, '24', 'Beige Metallic'	, 'https://static.rajamobil.com/resize/289x182/media/images/databasemobil/mobilbaru/color/hiace-premio-beige-metallic.png'),
    (NULL, '24', 'Silver Metallic'	, 'https://static.rajamobil.com/resize/289x182/media/images/databasemobil/mobilbaru/color/hiace-premio-silver-metallic.png'),
    (NULL, '24', 'White'	, 'https://static.rajamobil.com/resize/289x182/media/images/databasemobil/mobilbaru/color/hiace-premio-white.png'),
    (NULL, '25', 'Orange Metallic'	, 'https://static.rajamobil.com/resize/289x182/media/images/databasemobil/mobilbaru/color/FT86-Orange-Metallic-.png'),
    (NULL, '25', 'Crystal Black Silica'	, 'https://static.rajamobil.com/resize/289x182/media/images/databasemobil/mobilbaru/color/FT86-Crystal-Black-Silica-.png'),
    (NULL, '25', 'Dark Grey Metallic'	, 'https://static.rajamobil.com/resize/289x182/media/images/databasemobil/mobilbaru/color/FT86-Dark-Grey-Metallic-.png'),
    (NULL, '25', 'Galaxy Blue Silica'	, 'https://static.rajamobil.com/resize/289x182/media/images/databasemobil/mobilbaru/color/FT86-Galaxy-Blue-Silica-.png'),
    (NULL, '25', 'Lightning Red'	, 'https://static.rajamobil.com/resize/289x182/media/images/databasemobil/mobilbaru/color/FT86-Lightning-Red-.png'),
    (NULL, '25', 'Satin White Pearl'	, 'https://static.rajamobil.com/resize/289x182/media/images/databasemobil/mobilbaru/color/FT86-Satin-White-Pearl-.png'),
    (NULL, '26', 'Red Metallic'	, 'https://static.rajamobil.com/resize/289x182/media/images/databasemobil/mobilbaru/color/toyota-supra-gr-red-metallic.png'),
    (NULL, '26', 'Black Metallic'	, 'https://static.rajamobil.com/resize/289x182/media/images/databasemobil/mobilbaru/color/toyota-supra-gr-black-metallic.png'),
    (NULL, '26', 'Ice Gray Metallic'	, 'https://static.rajamobil.com/resize/289x182/media/images/databasemobil/mobilbaru/color/toyota-supra-gr-ice-grey-metallic.png'),
    (NULL, '26', 'Lightning Yellow'	, 'https://static.rajamobil.com/resize/289x182/media/images/databasemobil/mobilbaru/color/toyota-supra-gr-lightning-yellow.png'),
    (NULL, '26', 'White Metallic'	, 'https://static.rajamobil.com/resize/289x182/media/images/databasemobil/mobilbaru/color/toyota-supra-gr-white-metallic.png'),
    (NULL, '27', 'Attitude Black'	, 'https://static.rajamobil.com/resize/289x182/media/images/databasemobil/mobilbaru/color/all-new-camry-attitude-black.png'),
    (NULL, '27', 'Burning Black'	, 'https://static.rajamobil.com/resize/289x182/media/images/databasemobil/mobilbaru/color/all-new-camry-burning-black.png'),
    (NULL, '27', 'Graphite Me'	, 'https://static.rajamobil.com/resize/289x182/media/images/databasemobil/mobilbaru/color/all-new-camry-graphite-me.png'),
    (NULL, '27', 'Phantom Brown Metallic'	, 'https://static.rajamobil.com/resize/289x182/media/images/databasemobil/mobilbaru/color/all-new-camry-phantom-brown-metallic.png'),
    (NULL, '27', 'Platinum White Pearl'	, 'https://static.rajamobil.com/resize/289x182/media/images/databasemobil/mobilbaru/color/all-new-camry-platinum-white-pearl.png'),
    (NULL, '27', 'Red Mica'	, 'https://static.rajamobil.com/resize/289x182/media/images/databasemobil/mobilbaru/color/all-new-camry-red-mica.png'),
    (NULL, '27', 'Silver Metallic'	, 'https://static.rajamobil.com/resize/289x182/media/images/databasemobil/mobilbaru/color/all-new-camry-silver-metallic.png'),
    (NULL, '28', 'Attitude Black Mica'	, 'https://static.rajamobil.com/resize/289x182/media/images/databasemobil/mobilbaru/color/all-new-corolla-altis-attitude-black.png'),
    (NULL, '28', 'Celastite Gray'	, 'https://static.rajamobil.com/resize/289x182/media/images/databasemobil/mobilbaru/color/all-new-corolla-altis-calestite-gray.png'),
    (NULL, '28', 'Phantom Brown'	, 'https://static.rajamobil.com/resize/289x182/media/images/databasemobil/mobilbaru/color/all-new-corolla-altis-phantom-brown.png'),
    (NULL, '28', 'Red Mica Metallic'	, 'https://static.rajamobil.com/resize/289x182/media/images/databasemobil/mobilbaru/color/all-new-corolla-altis-red-mica.png'),
    (NULL, '28', 'Silver Metallic'	, 'https://static.rajamobil.com/resize/289x182/media/images/databasemobil/mobilbaru/color/all-new-corolla-altis-silver-metallic.png'),
    (NULL, '28', 'Super White'	, 'https://static.rajamobil.com/resize/289x182/media/images/databasemobil/mobilbaru/color/all-new-corolla-altis-super-white.png'),
    (NULL, '28', 'Pearl White'	, 'https://static.rajamobil.com/resize/289x182/media/images/databasemobil/mobilbaru/color/all-new-corolla-altis-white-pearl.png'),
    (NULL, '29', 'Graphite Metallic'	, 'https://static.rajamobil.com/resize/289x182/media/images/databasemobil/mobilbaru/color/1602112826-Graphite%20Metallic.png'),
    (NULL, '29', 'Metal Stream Metallic'	, 'https://static.rajamobil.com/resize/289x182/media/images/databasemobil/mobilbaru/color/1602112826-Metal%20Stream%20Metallic.png'),
    (NULL, '29', 'Nebula Blue Metallic'	, 'https://static.rajamobil.com/resize/289x182/media/images/databasemobil/mobilbaru/color/1602112826-Nebula%20Blue%20Metallic.png'),
    (NULL, '29', 'Platinum White Pearl'	, 'https://static.rajamobil.com/resize/289x182/media/images/databasemobil/mobilbaru/color/1602112826-Platinum%20White%20Pearl.png'),
    (NULL, '29', 'Red Mica Metallic'	, 'https://static.rajamobil.com/resize/289x182/media/images/databasemobil/mobilbaru/color/1602112826-Red%20Mica%20Metallic.png'),
    (NULL, '29', 'Attitude Black Metallic'	, 'https://static.rajamobil.com/resize/289x182/media/images/databasemobil/mobilbaru/color/1602112934-Attitude%20Black%20Metallic.png'),
    (NULL, '29', 'Celestite Gray Metallic'	, 'https://static.rajamobil.com/resize/289x182/media/images/databasemobil/mobilbaru/color/1602112934-Celestite%20Gray%20Metallic.png');